-- S-06 source-image-auto-purge migration for non-test environments (currently Neon).
--
-- Idempotent shape: safe to re-run; the FK swap is guarded so a re-run is a no-op
-- once the cascade is in place. H2 tests boot a fresh schema each run and pick up
-- the equivalent shape from ProposedEvent's @Index + @OnDelete annotations
-- (Hibernate ddl-auto=update does NOT alter existing FK constraints, which is why
-- the FK swap below must be run by hand).
--
-- Run order: this migration must land BEFORE Phase 3+ (the SourceImagePurgeService
-- sweep) deploys to that environment. Without the cascade, the bulk DELETE in
-- purgeEligible() will fail with a foreign-key violation.
--
-- See: context/changes/source-image-auto-purge/plan.md §"Migration Notes"

-- 1. Composite covering index for the purge predicate's PENDING-row probe.
CREATE INDEX IF NOT EXISTS ix_proposed_event_source_image_status
    ON proposed_event (source_image_id, status);

-- 2. Swap the proposed_event.source_image_id FK to ON DELETE CASCADE.
--    The original constraint was generated by Hibernate ddl-auto with a name
--    like 'fkXXXX...'. Discover it once per environment with `\d proposed_event`
--    in psql, then drop+re-add by name.
--
--    Re-running this block is safe iff fk_proposed_event_source_image already
--    exists with ON DELETE CASCADE — the DO block below is the explicit guard.
DO $$
DECLARE
    fk_name text;
    has_cascade boolean;
BEGIN
    SELECT conname,
           (confdeltype = 'c') AS cascades
      INTO fk_name, has_cascade
      FROM pg_constraint
     WHERE conrelid = 'proposed_event'::regclass
       AND contype  = 'f'
       AND (SELECT array_agg(attname ORDER BY attnum)
              FROM pg_attribute
             WHERE attrelid = conrelid
               AND attnum   = ANY(conkey)) = ARRAY['source_image_id']::name[]
     LIMIT 1;

    IF fk_name IS NULL THEN
        RAISE NOTICE 'No FK on proposed_event(source_image_id) found; nothing to swap.';
        RETURN;
    END IF;

    IF has_cascade THEN
        RAISE NOTICE 'FK % already ON DELETE CASCADE; no-op.', fk_name;
        RETURN;
    END IF;

    EXECUTE format('ALTER TABLE proposed_event DROP CONSTRAINT %I', fk_name);
    EXECUTE 'ALTER TABLE proposed_event
                 ADD CONSTRAINT fk_proposed_event_source_image
                 FOREIGN KEY (source_image_id) REFERENCES source_image(id)
                 ON DELETE CASCADE';
END $$;
